/*
AULA 1: Introdução a DEV T-SQL (Tratamento de Strings)
OBJETIVO: Aprender principais funções de tratamento de Strings e 
a combinação entre  elas.
CONTEÚDO:
	- Criação da base de dados AULA_DEV
	- Criação das Tabelas da Demo
	- Insert de Dados nas Tabelas
REQUISITOS: INSTALAR SQL SERVER 2017 (se possível)
	OBS: Versão 2016 em diante apenas 64bits

*/


CREATE DATABASE AULA_DEV

GO

USE AULA_DEV

GO

CREATE TABLE ALUNO
(
ID INT IDENTITY(1,1),
NOME VARCHAR(20) NOT NULL,
SOBRENOME VARCHAR(20) NOT NULL,
DATA_NASC DATE,
EMAIL VARCHAR(100),
CPF VARCHAR(20)
CONSTRAINT ID_ALUNO PRIMARY KEY (ID)
)

GO

INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Brunno','Araujo', '1985-11-25','brunno.teste@gmail.com','111-222-333-44')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Maria', 'Gomes', '1990-05-15','maria@gmail.com.br','222-333-444-55')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Joao', 'Ferreira','1995-01-10','joao@hotmail.com.br','333-444-555')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Jose', 'Alves','1992-02-05','jose@hotmail.com.br','444-555-666-77')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Claudio', 'Gonçalvez', '1990-05-15','claudio@gmail','555-666-777-')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Joana', 'Alvez', '1984-01-12','joana@hotmail','666-777-888-99')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Mario', 'Gomes', '1989-07-21','mario@uol.com.br','888-999-00')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL) VALUES ('Nome34', 'Teste', '1900-01-01','nome@teste.com.br')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL) VALUES ('T20este', 'Nome', '1900-11-10','teste@nome.com.br')
INSERT INTO ALUNO (NOME,SOBRENOME,DATA_NASC,EMAIL,CPF) VALUES ('Julia', 'Fonseca', '1995-05-01','julia@hotmail.com','111-888-999-00')

GO

CREATE TABLE NOTAS 
(
ALUNO VARCHAR(50),
NOTA DECIMAL(12,2)
)

GO

INSERT INTO NOTAS VALUES('João', 8.5)
INSERT INTO NOTAS VALUES('Claudio', 8.5)
INSERT INTO NOTAS VALUES('Maria', 10)
INSERT INTO NOTAS VALUES('João', 9.3)
INSERT INTO NOTAS VALUES('Joana', 7.2)